name: mirror

on: [push, delete]

jobs:
  mirror-to-CASUS:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: mirror-repository
      uses: spyoungtech/mirror-action@master
      with:
        REMOTE: 'ssh://git@github.com/casus/uqtestfuns.git'
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"
